{{- $cluster_name :=  default "mycluster" .Release.Name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $cluster_name }}-cluster-secret
  namespace: {{ coalesce .Values.overrideNamespace .Release.Namespace }}
stringData:
  rootUser: {{ .Values.credentials.root.user | default "root" | quote }}
  rootHost: {{ .Values.credentials.root.host | default "%%" | quote }}
  rootPassword: {{ required "credentials.root.password is required" .Values.credentials.root.password | quote }}
